Feature/leapr
njoy/lipservice pull request #22
Opened 2020-10-20 21:35 UTC by ameliajo

Added JSON reading for LEAPR. Also removed the requirement that Card20 must exist, since legacy LEAPR compiles even if you give no card20 comments.

2020-10-28 16:14 UTC, jlconlin requested changes
Great work. I really like the tests you have added. That helps know that everything is working properly.

Just a few minor changes to clean things up a bit.

2020-10-28 16:14 UTC, jlconlin commented on src/lipservice/LEAPR/test/LEAPR.test.cpp
> +            "smin"  :  1e-75,
I didn't see `smin` in the NJOY2016 LEAPR documentation. Does that mean the documentation is incorrect?

2020-10-28 16:14 UTC, jlconlin commented on src/lipservice/LEAPR/test/LEAPR.test.cpp
> +          nlohmann::json refJSON = R"({
I like this JSON representation. Looks nice and clean.

2020-10-28 16:14 UTC, jlconlin commented on src/lipservice/LEAPR/test/LEAPR.test.cpp
> +              {
Glad you tested one with multiple temperatures.

2020-10-28 16:14 UTC, jlconlin commented on src/lipservice/LEAPR/test/LEAPR.test.cpp
> +              "b7"     : 1,
Oh good, you remembered to test where there are secondary scatters.

2020-10-28 16:14 UTC, jlconlin commented on src/lipservice/src/LEAPR.hpp
> +
Please remove these extra lines.

2020-10-28 16:14 UTC, jlconlin commented on src/lipservice/src/LEAPR.hpp
> +    }
range-based for loops are easier than index-based loops.
```suggestion
    for( const auto& card : card20List ){
      card20Values.push_back( *(card.comment.value) );
    }
```

2020-10-28 16:58 UTC, ameliajo commented on src/lipservice/LEAPR/test/LEAPR.test.cpp
> +            "smin"  :  1e-75,
smin is the 5th value on LEAPR Card 4

2020-10-28 17:44 UTC, jlconlin commented on src/lipservice/LEAPR/test/LEAPR.test.cpp
> +            "smin"  :  1e-75,
Yep, the 2016 manual doesn't have this.

2020-10-28 18:15 UTC, ameliajo commented on src/lipservice/LEAPR/test/LEAPR.test.cpp
> +            "smin"  :  1e-75,
I might be mistaken, but it looks like it's [here](https://github.com/njoy/NJOY2016-manual/blob/master/njoy16.pdf) on page 668 of the document. Is there a preferred version of the manual we should be using? Sorry about the confusion

2020-10-28 18:23 UTC, jlconlin commented on src/lipservice/LEAPR/test/LEAPR.test.cpp
> +            "smin"  :  1e-75,
You are correct. I was looking at an older version of the manual.

2020-10-29 16:04 UTC, jlconlin commented on src/lipservice/src/LEAPR.hpp
> +    std::vector<std::string> card20Values;
This looks better.

2020-10-29 16:04 UTC, jlconlin approved these changes

2020-10-29 16:05 UTC, jlconlin commented
This looks good. We are moving *everything* to the new build system this morning.

2020-10-30 15:01 UTC, merged